In [3]:
%%markdown

# Sir's Exercises

.


# Sir's Exercises

.


In [5]:
import numpy as np

np.set_printoptions(precision=2)

In [6]:
def rand(row, col=1, max_val=100):
    if col == 1:
        return np.random.rand(row) * max_val
    else:
        return np.random.rand(row,col) * max_val

rand(4,4)

array([[ 6.56, 28.03, 84.15, 90.05],
       [40.73, 25.83, 84.19, 76.2 ],
       [34.46, 96.2 , 81.63, 45.92],
       [53.15, 43.86, 63.96, 96.76]])

In [7]:
rand(8)

array([54.71, 24.77,  1.84, 57.91, 27.19, 16.73, 19.69, 92.63])

In [11]:

a = rand(4,4)
print('a: '+ str(a))


a: [[31.86  2.3  36.5  87.5 ]
 [83.48 59.91 82.15  0.97]
 [47.14 44.66 64.6  52.25]
 [52.96  6.62 87.38 35.09]]


In [22]:
%%markdown

# Exercise 1: Find the sum and mean of the 2nd row
# Exercise 2: Find the sum and mean of all the rows
# Exercise 3: Find the mean(v) where v is a vector without using the mean()


# Exercise 1: Find the sum and mean of the 2nd row
# Exercise 2: Find the sum and mean of all the rows
# Exercise 3: Find the mean(v) where v is a vector without using the mean()


In [14]:
a.sum(axis=1)

array([158.16, 226.51, 208.65, 182.05])

In [15]:
a.sum(axis=1)[1]

226.50999465687187

In [16]:
a[1]

array([83.48, 59.91, 82.15,  0.97])

In [20]:
# ex1. sum of 2nd row
a[1].sum()

226.50999465687187

In [18]:
a.mean()

48.460894316971945

In [25]:
# ex1: mean of 2nd row
a[1].mean()

56.62749866421797

In [28]:
a

array([[31.86,  2.3 , 36.5 , 87.5 ],
       [83.48, 59.91, 82.15,  0.97],
       [47.14, 44.66, 64.6 , 52.25],
       [52.96,  6.62, 87.38, 35.09]])

In [29]:
a.max(axis=1)

array([87.5 , 83.48, 64.6 , 87.38])

In [23]:
# sum of all rows
a.sum(axis=1)

array([158.16, 226.51, 208.65, 182.05])

In [24]:
# mean of all rows
a.mean(axis=1)

array([39.54, 56.63, 52.16, 45.51])

In [35]:
def find_mean(arr):
    _sum = 0
    for item in arr:
        _sum += item
    
    mean = _sum / len(arr)
    return mean

find_mean(a[0])

39.5393821982186

In [34]:
a[0].mean()

39.5393821982186

In [33]:
a.mean()

48.460894316971945

In [39]:
%%markdown

# Exercise 5: Generate the vector [25 16 9 4 1] using a for loop similar to the code above
# Exercise 6: Given a vector like [1 4 9 16 25], output a vector containing only the elements that are even, i.e., [4 16]



# Exercise 5: Generate the vector [25 16 9 4 1] using a for loop similar to the code above
# Exercise 6: Given a vector like [1 4 9 16 25], output a vector containing only the elements that are even, i.e., [4 16]


In [42]:
b = (a%2 == 0)

In [47]:
a[b]

array([], dtype=float64)

In [48]:
x = np.arange(0,100)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [55]:
y = x[x % 2 == 0]

In [56]:
y

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])