In [2]:
import numpy as np
import matplotlib.pyplot as plt

np.set_printoptions(2)

In [3]:
x = np.array([1, 1.3, 1.6, 1.9, 2.2])

y = np.array([0.765197, 0.620086, 0.455402, 0.281818, 0.110362])


# Newton's Divided Difference Method

In [101]:
def ndd(xvals, yvals, memo={}):
    n = len(xvals)
    if n < 2:
        raise ValueError('array too short, please get help!')
    elif n == 2:
        val = (yvals[1] - yvals[0]) / (xvals[1] - xvals[0])
        print(val, "hi")
        return val
    else:
        val = (ndd(xvals[1:], yvals[1:]) - ndd(xvals[:-1], yvals[:-1])) / (xvals[-1] - xvals[0])
        print(val)
        return val
    


In [102]:
ndd(x,y)

-0.5715199999999995 hi
-0.5786133333333335 hi
0.011822222222223434
-0.5786133333333335 hi
-0.5489466666666668 hi
-0.04944444444444456
0.06807407407407554
-0.5786133333333335 hi
-0.5489466666666668 hi
-0.04944444444444456
-0.5489466666666668 hi
-0.4837033333333332 hi
-0.10873888888888932
0.06588271604938306
0.0018261316872437287


0.0018261316872437287

In [8]:
x

array([1. , 1.3, 1.6, 1.9, 2.2])

In [6]:
x[1:]



array([1.3, 1.6, 1.9, 2.2])

In [8]:
x[:-1]

array([1. , 1.3, 1.6, 1.9])

In [9]:
randint = np.random.randint

In [99]:
x2 = [2,3,6,7,9]
y2 = [15,39,243,375,771]

ndd(x2, y2)

198.0 hi
132.0 hi
22.0
132.0 hi
68.0 hi
16.0
1.0
132.0 hi
68.0 hi
16.0
68.0 hi
24.0 hi
11.0
1.0
0.0


0.0